### ISSUE TITLE
推荐使用 `devlive-community/openai-java-sdk`

### ISSUE THREAD

**Issue by qianmoQ** [NiuXiangQian/chatgpt-stream#11]
推荐使用 https://github.com/devlive-community/openai-java-sdk

**Comment by NiuXiangQian** [comment]
> 推荐使用 https://github.com/devlive-community/openai-java-sdk

嗯嗯 辛苦做出了sdk sdk可以更简洁的接入  我这里是早期手动接入了业务顺便分享了出来

**Comment by qianmoQ** [comment]
> > 推荐使用 https://github.com/devlive-community/openai-java-sdk
> 
> 嗯嗯 辛苦做出了sdk sdk可以更简洁的接入 我这里是早期手动接入了业务顺便分享了出来

欢迎参与 SDK 的贡献，目前已经支持多种 AI 服务商，后续会增加更多
