### ISSUE TITLE
流式返回会出现返回流断开情况. 断开那段时间 返回文字是空白，能否做一些等待？

### ISSUE THREAD

**Issue by linzhengwang** [NiuXiangQian/chatgpt-stream#2]
流式返回会出现返回流断开情况. 断开那段时间 返回文字是空白，能否做一些等待？

**Comment by NiuXiangQian** [comment]
> 流式返回会出现返回流断情情况。断开那段时间返回文字是空白，能不能做一些等候？

你好，’‘返回文字是空白‘’ 是openai返回的为空白吗？可以把返回结果贴上来我看一下，或者日志相关的。
