### ISSUE TITLE
请问我看代码里的string是单字符串，应当是无法做到上下文

### ISSUE THREAD

**Issue by nn5864312** [NiuXiangQian/chatgpt-stream#3]
OPENAI官方的3.5接口是传message的一个list过去，本项目是没有实现上下文的把应该

**Comment by NiuXiangQian** [comment]
其实把每次的对话使用Q: xxx  \n A:xxx  格式拼起来是可以被识别的
<img width="613" alt="image" src="https://user-images.githubusercontent.com/38468964/233345676-1555fb99-8f1e-4ee7-997b-32cf25690a69.png">

**Comment by NiuXiangQian** [comment]
> OPENAI官方的3.5接口是传message的一个list过去，本项目是没有实现上下文的把应该

其实把每次的对话使用Q: xxx \n A:xxx 格式拼起来是可以被识别的
![image](https://user-images.githubusercontent.com/38468964/233359533-29b94792-4163-43f7-91fe-ab6834439700.png)
