### ISSUE TITLE
前端sse监听error的事件，如何获取后端自定义的errorMsg

### ISSUE THREAD

**Issue by aoni2023** [NiuXiangQian/chatgpt-stream#5]
前端sse监听error的事件，如何获取后端自定义的errorMsg

**Comment by NiuXiangQian** [comment]
> 前端sse监听error的事件，如何获取后端自定义的errorMsg

我也尝试过在error的事件里获取错误信息，但是sse目前并不支持这样，建议在sse传输数据的时候 返回code 根据code做判断是否处理成功，然后从正常返回的数据里取出errorMsg. 比如 {code:1,errorMsg:'错误'}  {code:0,data:'数据'}
