### ISSUE TITLE
传入% 报错

### ISSUE THREAD

**Issue by yncylyetz** [NiuXiangQian/chatgpt-stream#6]
接口 /completions/stream 传入%报错。
改成PostMapping是可以的 Get方法出错

**Comment by NiuXiangQian** [comment]
> 接口 /completions/stream 传入%报错。 改成PostMapping是可以的 Get方法出错

是会出现这种问题，真实场景下使用也是建议改成post
改成post可能会导致h5页面无法调用接口，因为h5的sse是只能使用get方式

**Comment by NiuXiangQian** [comment]
> 接口 /completions/stream 传入%报错。 改成PostMapping是可以的 Get方法出错

目前支持了html post的方式
