### ISSUE TITLE
如何在云服务器部署自己的代理呢？

### ISSUE THREAD

**Issue by MrQiuHaHa** [NiuXiangQian/chatgpt-stream#7]
大佬，如题，我在自己客户端可以使用代理的客户端进行切换不同的国家，但是在云服务，没有GUI，我也不好安装代理客户端，那怎么办呢，我的是腾讯云

**Comment by NiuXiangQian** [comment]
> 大佬，如题，我在自己客户端可以使用代理的客户端进行切换不同的国家，但是在云服务，没有GUI，我也不好安装代理客户端，那怎么办呢，我的是腾讯云

在服务器上没法使用代理的话建议服务器选在香港或者境外
